[pytest]

# pytest 框架则提供了测试的组织、执行和管理功能

; ;表注释
;addopts = -vs
# 设置 pytest 运行时的命令行参数，-v详细模式
addopts = -vs --alluredir=allure-results
# 配置执行的用例位置
;testpaths = ./cases11
# 指定测试文件的命名规范，默认test_*.py 或 *_test.py
;python_files = case_*.py
# 指定测试类的命名规范，默认Test开头
;python_classes = Test
# 指定测试函数的命名规范，默认以test_开头
; python_functions = B_